import { useState } from "react"
import { Cpu, ShieldCheck } from "lucide-react"
import { ScrollArea } from "@/components/ui/scroll-area"
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from "@/components/ui/sheet"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import type { AutomationAgentProfileView, ControlPlaneSnapshot, DispatchIntent } from "@/lib/domain/control-plane"
import { MockNotice, PageIntro, StatusBadge, type StatusTone } from "./shared"

export function AgentsPage({ snapshot, view = "runtimes", onViewChange }: { snapshot: ControlPlaneSnapshot; dispatch: DispatchIntent; view?: string; onViewChange?: (view: string) => void }) {
  const [selectedId, setSelectedId] = useState<string | null>(null); const selected = snapshot.edgeAgents.find((agent) => agent.id === selectedId)
  return <><PageIntro eyebrow="AUTOMATION / AGENTS" title="Agent profiles" description="Edge runtime health is separate from logical profiles, their assignments, and declarative capabilities." actions={<StatusBadge label="No profile bypass" tone="info" />} /><MockNotice>Profiles are declarative metadata. They cannot access device protocols, credentials, arbitrary scripts, or bypass policy and leases.</MockNotice>
    <Tabs value={view} onValueChange={onViewChange}><TabsList className="rounded-none border border-border bg-background p-0" aria-label="Agent views"><TabsTrigger value="runtimes" className="rounded-none">Edge runtimes</TabsTrigger><TabsTrigger value="profiles" className="rounded-none">Logical profiles</TabsTrigger><TabsTrigger value="assignments" className="rounded-none">Assignments</TabsTrigger><TabsTrigger value="capabilities" className="rounded-none">Capabilities</TabsTrigger></TabsList>
      <TabsContent value="runtimes"><RuntimeTable snapshot={snapshot} onOpen={setSelectedId} /></TabsContent>
      <TabsContent value="profiles"><ProfileList profiles={snapshot.automationAgentProfiles} /></TabsContent>
      <TabsContent value="assignments"><div className="mt-4 border border-border"><table className="w-full text-left text-xs"><thead><tr className="border-b border-border text-[10px] uppercase tracking-[.08em] text-muted-foreground"><th className="p-3">Profile</th><th className="p-3">Assignment</th><th className="p-3">Trust</th></tr></thead><tbody>{snapshot.automationAgentProfiles.map((profile) => <tr key={profile.id} className="border-b border-border/70"><td className="p-3">{profile.id}</td><td className="p-3">{profile.assignmentSummary}</td><td className="p-3"><StatusBadge label={profile.trust} tone={trustTone(profile.trust)} /></td></tr>)}</tbody></table></div></TabsContent>
      <TabsContent value="capabilities"><div className="mt-4 grid gap-3 md:grid-cols-2">{snapshot.automationAgentProfiles.map((profile) => <div key={profile.id} className="border border-border p-4"><p className="text-xs font-semibold">{profile.id}</p><p className="mt-2 text-xs text-muted-foreground">{profile.capabilities.join(", ") || "No capabilities declared"}</p></div>)}</div></TabsContent>
    </Tabs>
    <Sheet open={Boolean(selected)} onOpenChange={(open) => !open && setSelectedId(null)}><SheetContent className="w-full rounded-none sm:max-w-xl"><SheetHeader className="border-b border-border"><SheetTitle>{selected?.displayName ?? "Runtime detail"}</SheetTitle><SheetDescription>Runtime state, health, and device bindings.</SheetDescription></SheetHeader>{selected ? <div className="space-y-4 p-4 text-xs"><div className="flex justify-between"><span>{selected.version}</span><StatusBadge label={selected.state} tone={selected.state === "active" ? "healthy" : "attention"} /></div><p>Last seen {selected.lastSeen}</p><div className="border-t border-border pt-3"><p className="font-semibold">Bound devices</p><p className="mt-1 text-muted-foreground">{selected.deviceIds.map((id) => snapshot.devices.find((device) => device.id === id)?.displayName ?? id).join(", ")}</p></div></div> : null}</SheetContent></Sheet>
  </> }
function RuntimeTable({ snapshot, onOpen }: { snapshot: ControlPlaneSnapshot; onOpen: (id: string) => void }) { return <ScrollArea className="mt-4 h-[min(65vh,700px)] border border-border"><table className="w-full min-w-[700px] text-left text-xs"><thead className="sticky top-0 bg-background"><tr className="border-b border-border text-[10px] uppercase tracking-[.08em] text-muted-foreground"><th className="p-3">Runtime</th><th className="p-3">State</th><th className="p-3">Version</th><th className="p-3">Devices</th><th className="p-3">Last seen</th></tr></thead><tbody>{snapshot.edgeAgents.map((agent) => <tr key={agent.id} className="border-b border-border/70 hover:bg-muted/50"><td className="p-3"><button onClick={() => onOpen(agent.id)} className="flex items-center gap-2 font-medium hover:underline"><Cpu className="size-3.5 text-primary" aria-hidden="true" />{agent.displayName}</button></td><td className="p-3"><StatusBadge label={agent.state} tone={agent.state === "active" ? "healthy" : "attention"} /></td><td className="drift-data p-3 text-[10px]">{agent.version}</td><td className="p-3">{agent.deviceIds.length}</td><td className="p-3 text-muted-foreground">{agent.lastSeen}</td></tr>)}</tbody></table></ScrollArea> }
function ProfileList({ profiles }: { profiles: readonly AutomationAgentProfileView[] }) { return <div className="mt-4 grid gap-3 md:grid-cols-2">{profiles.map((profile) => <div key={profile.id} className="border border-border p-4"><div className="flex justify-between gap-2"><p className="text-xs font-semibold">{profile.id}</p><StatusBadge label={profile.state} tone={profile.state === "published" ? "healthy" : "attention"} /></div><p className="mt-2 text-xs text-muted-foreground">{profile.personality}</p><div className="mt-3 flex gap-2"><ShieldCheck className="size-3.5 text-primary" aria-hidden="true" /><span className="text-[11px]">Trust: {profile.trust}</span></div></div>)}</div> }
function trustTone(value: AutomationAgentProfileView["trust"]): StatusTone { return value === "approved" ? "healthy" : value === "revoked" ? "danger" : "attention" }
