import { useState } from "react"
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from "@/components/ui/sheet"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import type { ControlPlaneSnapshot, DeviceView, DispatchIntent } from "@/lib/domain/control-plane"
import { stableIdentityLabel, type InspectionSection, type InspectionTab } from "./device-inspection"

export function DeviceInspectSheet({ device, tabs, activeTab, onTabChange, onClose, snapshot, dispatch }: { device?: DeviceView; tabs: readonly InspectionTab[]; activeTab: string; onTabChange: (tab: string) => void; onClose: () => void; snapshot: ControlPlaneSnapshot; dispatch: DispatchIntent }) {
  return <Sheet open={Boolean(device)} onOpenChange={(open) => { if (!open) onClose() }}><SheetContent className="w-full rounded-none sm:max-w-xl"><SheetHeader className="border-b border-border"><SheetTitle className="drift-data break-all text-sm">{device ? stableIdentityLabel(device) : "Device Inspection"}</SheetTitle><SheetDescription>Stable identity names this device. Transport endpoints are mutable projections and never title it.</SheetDescription></SheetHeader>{device ? <Tabs value={activeTab} onValueChange={(value) => onTabChange(String(value))} className="overflow-y-auto p-4"><TabsList className="h-auto flex-wrap rounded-none border border-border bg-background p-0" aria-label="Device Inspection Views">{tabs.map((tab) => <TabsTrigger key={tab.id} value={tab.id} className="rounded-none">{tab.label}</TabsTrigger>)}</TabsList>{tabs.map((tab) => <TabsContent key={tab.id} value={tab.id} className="space-y-5">{tab.sections.map((section, index) => <InspectionSectionView key={`${tab.id}-${section.title ?? index}`} section={section} />)}</TabsContent>)}<DeviceInputControls device={device} snapshot={snapshot} dispatch={dispatch} /></Tabs> : null}</SheetContent></Sheet>
}

function DeviceInputControls({ device, snapshot, dispatch }: { device: DeviceView; snapshot: ControlPlaneSnapshot; dispatch: DispatchIntent }) {
  const [mode, setMode] = useState<"tap" | "swipe" | "key">("tap"); const [status, setStatus] = useState(""); const [values, setValues] = useState({ x: "0", y: "0", startX: "0", startY: "0", endX: "0", endY: "0", durationMs: "300", width: "1080", height: "1920", keyCode: "4", observationToken: "" })
  const lease = snapshot.leases.find((item) => item.deviceId === device.id && item.state === "active"); const observation = snapshot.observations.find((item) => item.deviceId === device.id && item.freshnessToken)
  if (device.lifecycle === "retired" || device.controlEligibility !== "eligible" || !lease || !observation) return null
  const token = observation.freshnessToken; const set = (key: keyof typeof values, value: string) => setValues((current) => ({ ...current, [key]: value })); const num = (key: keyof typeof values) => Number(values[key])
  async function submit() { const common = { deviceId: device.id, confirmed: true }; const result = mode === "tap" ? await dispatch({ type: "submitDeviceTap", ...common, x: num("x"), y: num("y"), renderWidth: num("width"), renderHeight: num("height"), observationToken: values.observationToken || token }) : mode === "swipe" ? await dispatch({ type: "submitDeviceSwipe", ...common, startX: num("startX"), startY: num("startY"), endX: num("endX"), endY: num("endY"), durationMs: num("durationMs"), renderWidth: num("width"), renderHeight: num("height"), observationToken: values.observationToken || token }) : await dispatch({ type: "submitDeviceKeyEvent", ...common, keyCode: num("keyCode") }); setStatus(`${result.ok ? "Kernel outcome" : "Kernel refusal"}: ${result.message}`) }
  return <section aria-labelledby="device-input-title" className="mt-6 space-y-3 border-t border-border pt-5"><div><h3 id="device-input-title" className="text-[10px] font-semibold uppercase tracking-[.08em]">Device input</h3><p className="text-[11px] leading-5 text-muted-foreground">Lab/fake-device path only. Actions require this device's active lease and latest observation.</p></div><div className="flex flex-wrap gap-1" role="group" aria-label="Device input type">{(["tap", "swipe", "key"] as const).map((item) => <Button key={item} type="button" size="sm" variant={mode === item ? "default" : "outline"} onClick={() => setMode(item)}>{item === "key" ? "Key event" : item[0].toUpperCase() + item.slice(1)}</Button>)}</div>{mode === "tap" ? <div className="grid grid-cols-2 gap-2"><Input aria-label="Tap X" inputMode="numeric" value={values.x} onChange={(event) => set("x", event.target.value)} /><Input aria-label="Tap Y" inputMode="numeric" value={values.y} onChange={(event) => set("y", event.target.value)} /></div> : null}{mode === "swipe" ? <div className="grid grid-cols-2 gap-2">{(["startX", "startY", "endX", "endY", "durationMs"] as const).map((key) => <Input key={key} aria-label={key} inputMode="numeric" value={values[key]} onChange={(event) => set(key, event.target.value)} />)}</div> : null}{mode === "key" ? <Input aria-label="Key code" inputMode="numeric" value={values.keyCode} onChange={(event) => set("keyCode", event.target.value)} /> : null}{mode !== "key" ? <div className="grid grid-cols-2 gap-2"><Input aria-label="Render width" inputMode="numeric" value={values.width} onChange={(event) => set("width", event.target.value)} /><Input aria-label="Render height" inputMode="numeric" value={values.height} onChange={(event) => set("height", event.target.value)} /><Input className="col-span-2" aria-label="Observation token" value={values.observationToken || token} onChange={(event) => set("observationToken", event.target.value)} /></div> : null}<Button type="button" onClick={() => void submit()}>Submit to kernel</Button><p role="status" aria-live="polite" className="min-h-5 text-xs">{status}</p></section>
}
function InspectionSectionView({ section }: { section: InspectionSection }) { return <section className="space-y-3">{section.title ? <h3 className="text-[10px] font-semibold uppercase tracking-[.08em] text-muted-foreground">{section.title}</h3> : null}{section.description ? <p className="text-[11px] leading-5 text-muted-foreground">{section.description}</p> : null}{section.rows ? <dl className="grid gap-3 text-xs sm:grid-cols-2">{section.rows.map((entry) => <InspectionField key={entry.label} label={entry.label} value={entry.value} mono={entry.mono} />)}</dl> : null}{section.items ? <div className="space-y-3">{section.items.map((item) => <dl key={item.key} className="grid gap-3 border border-border p-3 text-xs sm:grid-cols-2">{item.rows.map((entry) => <InspectionField key={entry.label} label={entry.label} value={entry.value} mono={entry.mono} />)}</dl>)}</div> : null}</section> }
function InspectionField({ label, value, mono = false }: { label: string; value: string; mono?: boolean }) { return <div className="min-w-0"><dt className="text-[10px] uppercase tracking-[.08em] text-muted-foreground">{label}</dt><dd className={`mt-1 break-words ${mono ? "drift-data text-[11px]" : "text-xs"}`}>{value}</dd></div> }
