import { useMemo, useState } from "react"
import { BatteryCharging, CircleDot, KeyRound, Network, RefreshCw, Server, Smartphone } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import type { ControlPlaneSnapshot, DispatchIntent } from "@/lib/domain/control-plane"
import { DeviceIdentity, DeviceStatus, EmptyState, FailureBadge, FieldLabel, PageIntro, Panel, StatusBadge } from "./shared"

export function DevicesPage({ snapshot, dispatch }: { snapshot: ControlPlaneSnapshot; dispatch: DispatchIntent }) {
  const [query, setQuery] = useState("")
  const devices = useMemo(() => snapshot.devices.filter((device) => `${device.displayName} ${device.stableIdentity} ${device.location}`.toLowerCase().includes(query.toLowerCase())), [query, snapshot.devices])
  return (
    <>
      <PageIntro eyebrow="INVENTORY / DEVICES" title="Device registry" description="Inspect stable device identity, current transport, edge-agent truth, and observation freshness as separate projections." actions={<Button variant="outline" size="sm" onClick={() => dispatch({ type: "refresh" })}><RefreshCw className="size-3.5" aria-hidden="true" />Refresh projection</Button>} />
      <div className="mb-6 grid gap-3 sm:grid-cols-3">
        <Summary label="Registered identities" value={String(snapshot.devices.length)} detail="Canonical device records" />
        <Summary label="Current endpoints" value={String(snapshot.endpoints.filter((endpoint) => endpoint.state === "current").length)} detail="Mutable transport projection" />
        <Summary label="Fresh observations" value={String(snapshot.observations.filter((observation) => observation.captureStatus === "complete").length)} detail="Sanitized fixture snapshots" />
      </div>
      <Panel title="Device truth" description="Stable ID and mutable endpoint are never used interchangeably." action={<div className="relative w-56 max-w-full"><FieldLabel htmlFor="device-registry-search">Filter devices</FieldLabel><input id="device-registry-search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Name, ID, or location" className="mt-1 h-8 w-full rounded-none border border-input bg-background px-2 text-xs outline-none focus:border-primary focus:ring-2 focus:ring-primary/20" /></div>}>
        {devices.length === 0 ? <EmptyState label="No devices match this filter" detail="Try a stable identity, display name, or location." /> : <div className="overflow-x-auto"><table className="w-full min-w-[850px] border-collapse text-left text-xs"><caption className="sr-only">Registered device identities and their current projections</caption><thead><tr className="border-b border-border text-[10px] uppercase tracking-[0.08em] text-muted-foreground"><th className="px-3 pb-3 font-semibold">Device identity</th><th className="px-3 pb-3 font-semibold">Lifecycle</th><th className="px-3 pb-3 font-semibold">Status</th><th className="px-3 pb-3 font-semibold">Edge agent</th><th className="px-3 pb-3 font-semibold">Endpoint</th><th className="px-3 pb-3 font-semibold">Observation</th></tr></thead><tbody>{devices.map((device) => <tr key={device.id} className="border-b border-border/70 align-top last:border-0"><td className="px-3 py-4"><div className="flex items-start gap-2"><Smartphone className="mt-0.5 size-4 text-primary" aria-hidden="true" /><DeviceIdentity device={device} /></div><p className="mt-2 text-[11px] text-muted-foreground">{device.location}</p></td><td className="px-3 py-4"><StatusBadge label={device.lifecycle} tone={device.lifecycle === "active" ? "healthy" : "neutral"} /></td><td className="px-3 py-4"><DeviceStatus device={device} /><p className="mt-2 text-[11px] text-muted-foreground">seen {device.lastSeen}</p></td><td className="px-3 py-4"><p className="font-medium">{device.agentId}</p><p className="mt-1 text-[11px] text-muted-foreground">{snapshot.edgeAgents.find((agent) => agent.id === device.agentId)?.state ?? "unknown"}</p></td><td className="px-3 py-4"><p className="font-medium">{device.endpointId}</p><p className="drift-data mt-1 text-[11px] text-muted-foreground">{snapshot.endpoints.find((endpoint) => endpoint.id === device.endpointId)?.host ?? "—"}:{snapshot.endpoints.find((endpoint) => endpoint.id === device.endpointId)?.port ?? "—"}</p></td><td className="px-3 py-4"><div className="flex items-center gap-1.5"><CircleDot className="size-3.5 text-primary" aria-hidden="true" /><span>{snapshot.observations.find((observation) => observation.deviceId === device.id)?.captureStatus ?? "unknown"}</span></div><p className="drift-data mt-1 text-[10px] text-muted-foreground">{snapshot.observations.find((observation) => observation.deviceId === device.id)?.freshnessToken ?? "—"}</p></td></tr>)}</tbody></table></div>}
      </Panel>
      <div className="mt-6 grid gap-6 xl:grid-cols-2">
        <Panel title="Edge-agent truth" description="Runtime health is distinct from device lifecycle and workflow state.">
          <div className="space-y-3">{snapshot.edgeAgents.map((agent) => <div key={agent.id} className="border border-border p-3"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-medium">{agent.displayName}</p><p className="drift-data mt-1 text-[10px] text-muted-foreground">{agent.id} · {agent.version}</p></div><StatusBadge label={agent.state} tone={agent.state === "active" ? "healthy" : agent.state === "unhealthy" ? "attention" : "neutral"} /></div><div className="mt-3 flex items-center gap-4 text-[11px] text-muted-foreground"><span className="flex items-center gap-1"><Server className="size-3" aria-hidden="true" />{agent.deviceIds.length} devices</span><span>last heartbeat {agent.lastSeen}</span></div></div>)}</div>
        </Panel>
        <Panel title="Endpoint history" description="Current transport is a projection; superseded observations remain visible for review.">
          <div className="space-y-3">{snapshot.endpoints.map((endpoint) => { const device = snapshot.devices.find((candidate) => candidate.id === endpoint.deviceId); return <div key={endpoint.id} className="border border-border p-3"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-medium">{device?.displayName ?? endpoint.deviceId}</p><p className="drift-data mt-1 text-[10px] text-muted-foreground">{endpoint.id}</p></div><StatusBadge label={endpoint.state} tone={endpoint.state === "current" ? "healthy" : "neutral"} /></div><div className="mt-3 grid grid-cols-2 gap-3 text-[11px]"><div><span className="text-muted-foreground">Stable serial</span><p className="drift-data mt-1">{endpoint.serial}</p></div><div><span className="text-muted-foreground">Transport</span><p className="drift-data mt-1">{endpoint.host}:{endpoint.port}</p></div></div></div> })}</div>
        </Panel>
      </div>
      <div className="mt-6"><Panel title="Lease truth" description="Control sessions and device leases are separate from device health and endpoint state."><div className="overflow-x-auto"><table className="w-full min-w-[650px] border-collapse text-left text-xs"><caption className="sr-only">Device lease projections</caption><thead><tr className="border-b border-border text-[10px] uppercase tracking-[0.08em] text-muted-foreground"><th className="px-3 pb-3">Device</th><th className="px-3 pb-3">Lease</th><th className="px-3 pb-3">Holder</th><th className="px-3 pb-3">Fencing token</th><th className="px-3 pb-3">State</th><th className="px-3 pb-3">Expires</th></tr></thead><tbody>{snapshot.leases.map((lease) => <tr key={lease.id} className="border-b border-border/70 last:border-0"><td className="px-3 py-3"><div className="flex items-center gap-2"><KeyRound className="size-3.5 text-primary" aria-hidden="true" />{snapshot.devices.find((device) => device.id === lease.deviceId)?.displayName ?? lease.deviceId}</div></td><td className="drift-data px-3 py-3">{lease.id}</td><td className="px-3 py-3">{lease.holder}</td><td className="drift-data px-3 py-3">{lease.fencingToken}</td><td className="px-3 py-3"><StatusBadge label={lease.state} tone={lease.state === "active" ? "healthy" : lease.state === "revoked" ? "danger" : "neutral"} /></td><td className="px-3 py-3 text-[11px] text-muted-foreground">{lease.expiresAt}</td></tr>)}</tbody></table></div></Panel></div>
      <div className="mt-6"><Panel title="Account truth" description="Account references are non-secret metadata and remain distinct from device, lease, and workflow projections."><div className="grid gap-3 md:grid-cols-2">{snapshot.accounts.map((account) => <div key={account.id} className="border border-border p-3"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-medium">{account.label}</p><p className="drift-data mt-1 text-[10px] text-muted-foreground">{account.id} · {account.externalReference}</p></div><StatusBadge label={account.state} tone={account.state === "active" ? "healthy" : "attention"} /></div><dl className="mt-3 grid grid-cols-2 gap-3 text-[11px]"><div><dt className="text-muted-foreground">Assigned device</dt><dd className="mt-1">{account.assignedDeviceId ? snapshot.devices.find((device) => device.id === account.assignedDeviceId)?.displayName ?? account.assignedDeviceId : "Unassigned"}</dd></div><div><dt className="text-muted-foreground">Service state</dt><dd className="mt-1">{account.serviceState}</dd></div><div className="col-span-2"><dt className="text-muted-foreground">Last run</dt><dd className="mt-1">{account.lastRun}</dd></div></dl></div>)}</div></Panel></div>
      <div className="mt-6 grid gap-6 xl:grid-cols-2"><Panel title="Battery and platform" description="Inventory facts are informational and do not authorize control."><div className="grid gap-3 sm:grid-cols-2">{snapshot.devices.map((device) => <Card key={device.id} className="rounded-none border border-border bg-background"><CardContent className="p-3"><div className="flex items-center justify-between gap-2"><span className="text-xs font-medium">{device.displayName}</span><span className="drift-data text-[10px] text-muted-foreground">{device.platformVersion}</span></div><div className="mt-3 flex items-center gap-2 text-xs"><BatteryCharging className="size-3.5 text-primary" aria-hidden="true" />{device.batteryPercent}%<span className="ml-auto text-[10px] text-muted-foreground">{device.latencyMs ? `${device.latencyMs} ms` : "offline"}</span></div><div className="mt-2 h-1 bg-muted"><div className={`h-full ${device.batteryPercent < 25 ? "bg-amber-600" : "bg-primary"}`} style={{ width: `${device.batteryPercent}%` }} /></div></CardContent></Card>)}</div></Panel><Panel title="Observation coverage" description="Freshness tokens and sanitized evidence remain separate from transport data."><div className="space-y-3">{snapshot.observations.map((observation) => <div key={observation.id} className="flex items-center justify-between gap-3 border-b border-border pb-3 last:border-0 last:pb-0"><div><p className="text-xs font-medium">{snapshot.devices.find((device) => device.id === observation.deviceId)?.displayName ?? observation.deviceId}</p><p className="drift-data mt-1 text-[10px] text-muted-foreground">{observation.source} · {observation.freshnessToken}</p></div><div className="flex items-center gap-2"><StatusBadge label={observation.captureStatus} tone={observation.captureStatus === "complete" ? "healthy" : "attention"} /><FailureBadge failureClass={observation.failureClass} /></div></div>)}</div></Panel></div>
      <div className="mt-6 flex items-start gap-2 border-t border-border pt-4 text-xs leading-5 text-muted-foreground"><Network className="mt-0.5 size-4 shrink-0 text-primary" aria-hidden="true" />Transport rows are mock-only and use documentation addresses. No ADB, shell, network socket, or device library is bundled in the console.</div>
    </>
  )
}

function Summary({ label, value, detail }: { label: string; value: string; detail: string }) {
  return <Card className="rounded-none border border-border bg-card"><CardContent className="p-4"><p className="font-mono text-[10px] uppercase tracking-[0.1em] text-muted-foreground">{label}</p><p className="drift-data mt-1 text-2xl font-semibold">{value}</p><p className="mt-1 text-[11px] text-muted-foreground">{detail}</p></CardContent></Card>
}
