import { useMemo, useState } from "react"
import { RefreshCw, Search, Smartphone, Trash2 } from "lucide-react"
import { AlertDialog, AlertDialogContent, AlertDialogTrigger } from "@/components/ui/alert-dialog"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { ScrollArea } from "@/components/ui/scroll-area"
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from "@/components/ui/sheet"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import type { ControlPlaneSnapshot, DeviceView, DispatchIntent } from "@/lib/domain/control-plane"
import { DataTablePagination, DeviceIdentity, DeviceStatus, EmptyState, PageIntro, StatusBadge } from "./shared"

type Filter = "all" | "online" | "attention" | "replaced" | "retired"
const filters: { value: Filter; label: string }[] = [{ value: "all", label: "All" }, { value: "online", label: "Online" }, { value: "attention", label: "Needs Attention" }, { value: "replaced", label: "Replaced" }, { value: "retired", label: "Retired" }]

export function DevicesPage({ snapshot, dispatch, view = "all", onViewChange }: { snapshot: ControlPlaneSnapshot; dispatch: DispatchIntent; view?: string; onViewChange?: (view: Filter) => void }) {
  const filter: Filter = isFilter(view) ? view : "all"
  const [query, setQuery] = useState(""); const [selectedId, setSelectedId] = useState<string | null>(null); const [selected, setSelected] = useState<string[]>([]); const [message, setMessage] = useState(""); const [page, setPage] = useState(0); const [pageSize, setPageSize] = useState(5); const [detailView, setDetailView] = useState("overview")
  const devices = useMemo(() => snapshot.devices.filter((device) => matches(device, filter) && searchable(device).includes(query.trim().toLowerCase())), [snapshot.devices, filter, query])
  const pageCount = Math.max(1, Math.ceil(devices.length / pageSize)); const safePage = Math.min(page, pageCount - 1); const visibleDevices = devices.slice(safePage * pageSize, (safePage + 1) * pageSize); const detail = snapshot.devices.find((device) => device.id === selectedId)
  function toggle(id: string) { setSelected((current) => current.includes(id) ? current.filter((value) => value !== id) : [...current, id]) }
  function refresh() { setMessage(dispatch({ type: "refresh" }).message) }
  return <><PageIntro eyebrow="INVENTORY / DEVICES" title="Device Registry" description="Stable identities are primary; endpoint and lifecycle history are secondary, inspectable projections." actions={<Button variant="outline" size="sm" onClick={refresh}><RefreshCw className="size-3.5" aria-hidden="true" />Refresh</Button>} />
    <Tabs value={filter} onValueChange={(next) => { if (isFilter(next)) { setPage(0); onViewChange?.(next) } }}><div className="flex flex-wrap items-center justify-between gap-3 border-y border-border py-3"><TabsList className="h-auto max-w-full flex-wrap justify-start rounded-none bg-transparent p-0" aria-label="Device Registry Views">{filters.map((item) => <TabsTrigger key={item.value} value={item.value} className="rounded-none">{item.label}</TabsTrigger>)}</TabsList><div className="relative w-full sm:w-64"><Search className="absolute left-2 top-2.5 size-3.5 text-muted-foreground" aria-hidden="true" /><Input aria-label="Search Device Registry" value={query} onChange={(event) => { setQuery(event.target.value); setPage(0) }} placeholder="Search devices" className="h-9 rounded-none pl-7 text-xs" /></div></div>
      <TabsContent value={filter} className="mt-4"><div className="flex flex-wrap items-center gap-2 border border-border bg-muted/30 p-3"><span className="mr-auto text-xs"><span className="drift-data font-semibold">{selected.length}</span> selected</span><Button size="sm" variant="outline" disabled={selected.length === 0} onClick={() => setMessage("Bulk move is unavailable in this mock registry.")}>Bulk Move</Button><AlertDialog><AlertDialogTrigger render={<Button size="sm" variant="outline" disabled={selected.length === 0} />}><Trash2 className="size-3.5" aria-hidden="true" />Remove Terminal Records</AlertDialogTrigger><AlertDialogContent title="Remove Terminal Device Records?" description="This mock-only confirmation preserves active records. No persistent data is changed in this browser prototype." confirmLabel="Confirm Mock Removal" onConfirm={() => setMessage("Mock removal confirmed; no registry data changed.")} /></AlertDialog><span aria-live="polite" className="w-full text-[11px] text-muted-foreground sm:w-auto">{message}</span></div>
      {devices.length === 0 ? <EmptyState label="No Devices in This View" detail="Change the active view or search term." /> : <><ScrollArea className="h-[min(62vh,680px)] border-x border-t border-border"><table className="w-full min-w-[760px] border-collapse text-left text-xs"><caption className="sr-only">Device Registry</caption><thead className="sticky top-0 bg-background"><tr className="border-b border-border text-[10px] uppercase tracking-[.08em] text-muted-foreground"><th className="w-10 p-3">Select</th><th className="p-3">Identity</th><th className="p-3">Lifecycle</th><th className="p-3">Health</th><th className="p-3">Endpoint</th><th className="p-3">Last Seen</th><th className="p-3"><span className="sr-only">Actions</span></th></tr></thead><tbody>{visibleDevices.map((device) => <DeviceRow key={device.id} device={device} endpoint={snapshot.endpoints.find((endpoint) => endpoint.id === device.endpointId)?.host ?? "—"} checked={selected.includes(device.id)} onToggle={toggle} onInspect={() => { setSelectedId(device.id); setDetailView("overview") }} />)}</tbody></table></ScrollArea><DataTablePagination page={safePage} pageSize={pageSize} total={devices.length} onPageChange={setPage} onPageSizeChange={(nextPageSize) => { setPageSize(nextPageSize); setPage(0) }} /></>}</TabsContent></Tabs>
    <Sheet open={Boolean(detail)} onOpenChange={(open) => !open && setSelectedId(null)}><SheetContent className="w-full rounded-none sm:max-w-xl"><SheetHeader className="border-b border-border"><SheetTitle>{detail?.displayName ?? "Device Detail"}</SheetTitle><SheetDescription>Stable identity and mutable projections remain distinct.</SheetDescription></SheetHeader>{detail ? <Tabs value={detailView} onValueChange={setDetailView} className="p-4"><TabsList className="h-auto flex-wrap rounded-none border border-border bg-background p-0" aria-label="Device Detail Views"><TabsTrigger value="overview" className="rounded-none">Overview</TabsTrigger><TabsTrigger value="activity" className="rounded-none">Activity</TabsTrigger><TabsTrigger value="health" className="rounded-none">Health</TabsTrigger><TabsTrigger value="lifecycle" className="rounded-none">Lifecycle</TabsTrigger><TabsTrigger value="endpoints" className="rounded-none">Endpoints</TabsTrigger></TabsList><TabsContent value="overview" className="space-y-3"><DeviceIdentity device={detail} /><p className="text-xs text-muted-foreground">{detail.location} · {detail.platformVersion}</p><DeviceStatus device={detail} /></TabsContent><TabsContent value="activity"><p className="text-xs">{detail.workflow}</p></TabsContent><TabsContent value="health"><p className="text-xs">Battery {detail.batteryPercent}% · latency {detail.latencyMs} ms</p></TabsContent><TabsContent value="lifecycle"><p className="text-xs">Lifecycle history is retained behind this detail view. Current state: {detail.lifecycle}.</p></TabsContent><TabsContent value="endpoints"><div className="space-y-2">{snapshot.endpoints.filter((endpoint) => endpoint.deviceId === detail.id).map((endpoint) => <p key={endpoint.id} className="border border-border p-3 text-xs">{endpoint.state} · {endpoint.host}:{endpoint.port}</p>)}</div></TabsContent></Tabs> : null}</SheetContent></Sheet></>
}
function DeviceRow({ device, endpoint, checked, onToggle, onInspect }: { device: DeviceView; endpoint: string; checked: boolean; onToggle: (id: string) => void; onInspect: () => void }) { return <tr className="border-b border-border/70 hover:bg-muted/50 focus-within:bg-muted/50"><td className="p-3"><input aria-label={`Select ${device.displayName}`} type="checkbox" checked={checked} onChange={() => onToggle(device.id)} /></td><td className="p-3"><DeviceIdentity device={device} /></td><td className="p-3"><StatusBadge label={device.lifecycle} tone={device.lifecycle === "active" ? "healthy" : "neutral"} /></td><td className="p-3"><DeviceStatus device={device} /></td><td className="drift-data p-3 text-[10px]">{endpoint}</td><td className="p-3 text-muted-foreground">{device.lastSeen}</td><td className="p-3 text-right"><Button size="sm" variant="outline" onClick={onInspect}><Smartphone className="size-3.5" aria-hidden="true" />Inspect</Button></td></tr> }
function isFilter(value: string): value is Filter { return filters.some((filter) => filter.value === value) }
function searchable(device: DeviceView) { return `${device.displayName} ${device.stableIdentity} ${device.location}`.toLowerCase() }
function matches(device: DeviceView, filter: Filter) { return filter === "all" || filter === "online" && device.status === "online" || filter === "attention" && device.status !== "online" || filter === "replaced" && device.lifecycle === "unavailable" || filter === "retired" && device.lifecycle === "retired" }
