import { useMemo, useState } from "react"
import { RefreshCw, Search, Smartphone, Trash2 } from "lucide-react"
import { AlertDialog, AlertDialogContent, AlertDialogTrigger } from "@/components/ui/alert-dialog"
import { Button } from "@/components/ui/button"
import { ScrollArea } from "@/components/ui/scroll-area"
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from "@/components/ui/sheet"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import type { ControlPlaneSnapshot, DeviceView, DispatchIntent } from "@/lib/domain/control-plane"
import { DeviceIdentity, DeviceStatus, EmptyState, PageIntro, StatusBadge } from "./shared"

type Filter = "all" | "online" | "attention" | "replaced" | "retired"
export function DevicesPage({ snapshot, dispatch }: { snapshot: ControlPlaneSnapshot; dispatch: DispatchIntent }) {
  const [filter, setFilter] = useState<Filter>("all"); const [query, setQuery] = useState(""); const [selectedId, setSelectedId] = useState<string | null>(null); const [selected, setSelected] = useState<string[]>([]); const [message, setMessage] = useState("")
  const devices = useMemo(() => snapshot.devices.filter((device) => matches(device, filter) && `${device.displayName} ${device.stableIdentity} ${device.location}`.toLowerCase().includes(query.toLowerCase())), [snapshot.devices, filter, query])
  const detail = snapshot.devices.find((device) => device.id === selectedId)
  function toggle(id: string) { setSelected((current) => current.includes(id) ? current.filter((value) => value !== id) : [...current, id]) }
  return <><PageIntro eyebrow="INVENTORY / DEVICES" title="Device registry" description="Stable identities are primary; endpoint and lifecycle history are secondary, inspectable projections." actions={<Button variant="outline" size="sm" onClick={() => dispatch({ type: "refresh" })}><RefreshCw className="size-3.5" aria-hidden="true" />Refresh</Button>} />
    <Tabs value={filter} onValueChange={(value) => setFilter(value as Filter)}><div className="flex flex-wrap items-center justify-between gap-3 border-y border-border py-3"><TabsList className="rounded-none bg-transparent p-0" aria-label="Device registry filters">{(["all", "online", "attention", "replaced", "retired"] as const).map((value) => <TabsTrigger key={value} value={value} className="rounded-none capitalize">{value === "attention" ? "Needs attention" : value}</TabsTrigger>)}</TabsList><div className="relative"><Search className="absolute left-2 top-2 size-3.5 text-muted-foreground" aria-hidden="true" /><input aria-label="Filter device registry" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Filter devices" className="h-8 rounded-none border border-input bg-background pl-7 pr-2 text-xs" /></div></div>
      <TabsContent value={filter} className="mt-4"><div className="flex flex-wrap items-center gap-2 border border-border bg-muted/30 p-3"><span className="mr-auto text-xs"><span className="drift-data font-semibold">{selected.length}</span> selected</span><Button size="sm" variant="outline" disabled={selected.length === 0} onClick={() => setMessage("Bulk action is intentionally unavailable in the mock registry.")}>Bulk move</Button><AlertDialog><AlertDialogTrigger render={<Button size="sm" variant="outline" disabled={selected.length === 0} />}><Trash2 className="size-3.5" aria-hidden="true" />Remove terminal records</AlertDialogTrigger><AlertDialogContent title="Remove terminal device records?" description="This mock-only confirmation preserves active records. No persistent data is changed in this browser prototype." confirmLabel="Confirm mock removal" onConfirm={() => setMessage("Mock removal confirmed; no registry data changed.")} /></AlertDialog><span aria-live="polite" className="w-full text-[11px] text-muted-foreground sm:w-auto">{message}</span></div>
      <ScrollArea className="mt-3 h-[min(62vh,680px)] border border-border"><table className="w-full min-w-[760px] border-collapse text-left text-xs"><caption className="sr-only">Device registry</caption><thead className="sticky top-0 bg-background"><tr className="border-b border-border text-[10px] uppercase tracking-[.08em] text-muted-foreground"><th className="w-10 p-3">Select</th><th className="p-3">Identity</th><th className="p-3">Lifecycle</th><th className="p-3">Health</th><th className="p-3">Endpoint</th><th className="p-3">Last seen</th></tr></thead><tbody>{devices.map((device) => <tr key={device.id} className="border-b border-border/70 hover:bg-muted/50"><td className="p-3"><input aria-label={`Select ${device.displayName}`} type="checkbox" checked={selected.includes(device.id)} onChange={() => toggle(device.id)} /></td><td className="p-3"><button className="flex text-left focus-visible:outline-2 focus-visible:outline-primary" onClick={() => setSelectedId(device.id)}><Smartphone className="mr-2 mt-0.5 size-4 text-primary" aria-hidden="true" /><DeviceIdentity device={device} /></button></td><td className="p-3"><StatusBadge label={device.lifecycle} tone={device.lifecycle === "active" ? "healthy" : "neutral"} /></td><td className="p-3"><DeviceStatus device={device} /></td><td className="drift-data p-3 text-[10px]">{snapshot.endpoints.find((endpoint) => endpoint.id === device.endpointId)?.host ?? "—"}</td><td className="p-3 text-muted-foreground">{device.lastSeen}</td></tr>)}</tbody></table>{devices.length === 0 ? <EmptyState label="No devices in this view" detail="Change the active filter or search." /> : null}</ScrollArea></TabsContent></Tabs>
    <Sheet open={Boolean(detail)} onOpenChange={(open) => !open && setSelectedId(null)}><SheetContent className="w-full rounded-none sm:max-w-xl"><SheetHeader className="border-b border-border"><SheetTitle>{detail?.displayName ?? "Device detail"}</SheetTitle><SheetDescription>Stable identity and mutable projections remain distinct.</SheetDescription></SheetHeader>{detail ? <Tabs defaultValue="overview" className="p-4"><TabsList className="rounded-none border border-border bg-background p-0"><TabsTrigger value="overview" className="rounded-none">Overview</TabsTrigger><TabsTrigger value="activity" className="rounded-none">Activity</TabsTrigger><TabsTrigger value="health" className="rounded-none">Health</TabsTrigger><TabsTrigger value="lifecycle" className="rounded-none">Lifecycle</TabsTrigger><TabsTrigger value="endpoints" className="rounded-none">Endpoints</TabsTrigger></TabsList><TabsContent value="overview" className="space-y-3"><DeviceIdentity device={detail} /><p className="text-xs text-muted-foreground">{detail.location} · {detail.platformVersion}</p><DeviceStatus device={detail} /></TabsContent><TabsContent value="activity"><p className="text-xs">{detail.workflow}</p></TabsContent><TabsContent value="health"><p className="text-xs">Battery {detail.batteryPercent}% · latency {detail.latencyMs} ms</p></TabsContent><TabsContent value="lifecycle"><p className="text-xs">Lifecycle history is retained behind this detail view. Current state: {detail.lifecycle}.</p></TabsContent><TabsContent value="endpoints"><div className="space-y-2">{snapshot.endpoints.filter((endpoint) => endpoint.deviceId === detail.id).map((endpoint) => <p key={endpoint.id} className="border border-border p-3 text-xs">{endpoint.state} · {endpoint.host}:{endpoint.port}</p>)}</div></TabsContent></Tabs> : null}</SheetContent></Sheet>
  </> }
function matches(device: DeviceView, filter: Filter) { return filter === "all" || filter === "online" && device.status === "online" || filter === "attention" && device.status !== "online" || filter === "replaced" && device.lifecycle === "unavailable" || filter === "retired" && device.lifecycle === "retired" }
