import { useMemo, useState } from "react"
import { FileText, Filter, ShieldCheck, Waypoints } from "lucide-react"
import type { ControlPlaneSnapshot, EventKind } from "@/lib/domain/control-plane"
import { FailureBadge, FieldLabel, MockNotice, PageIntro, Panel, StatusBadge } from "./shared"

export function EventsPage({ snapshot }: { snapshot: ControlPlaneSnapshot }) {
  const [kind, setKind] = useState<EventKind | "all">("all")
  const [query, setQuery] = useState("")
  const events = useMemo(() => snapshot.events.filter((event) => (kind === "all" || event.kind === kind) && `${event.name} ${event.actor} ${event.resourceId}`.toLowerCase().includes(query.toLowerCase())), [kind, query, snapshot.events])
  return (
    <>
      <PageIntro eyebrow="OBSERVABILITY / EVENTS" title="Events and audit" description="Follow operational facts, actor attribution, correlation IDs, and typed failures without exposing raw payloads or sensitive evidence." actions={<StatusBadge label="Redacted view" tone="info" />} />
      <MockNotice>Payload bodies, screenshots, credentials, and device protocol data are omitted from this browser view. Only bounded, sanitized metadata is rendered.</MockNotice>
      <div className="mb-6 grid gap-3 sm:grid-cols-3"><Summary icon={Waypoints} label="Operational events" value={String(snapshot.events.filter((event) => event.kind === "operational").length)} detail="State and runtime facts" /><Summary icon={ShieldCheck} label="Audit events" value={String(snapshot.events.filter((event) => event.kind === "audit").length)} detail="Actor-attributed changes" /><Summary icon={FileText} label="Failure labels" value={String(snapshot.events.filter((event) => event.failureClass).length)} detail="Typed, searchable outcomes" /></div>
      <Panel title="Event timeline" description="Operational and audit events share an envelope but retain distinct meaning." action={<div className="flex flex-wrap items-end gap-2"><div><FieldLabel htmlFor="event-kind">Kind</FieldLabel><select id="event-kind" value={kind} onChange={(event) => { const value = event.target.value; if (isEventKind(value)) setKind(value) }} className="mt-1 h-8 rounded-none border border-input bg-background px-2 text-xs outline-none focus:border-primary focus:ring-2 focus:ring-primary/20"><option value="all">All events</option><option value="operational">Operational</option><option value="audit">Audit</option></select></div><div className="relative"><Filter className="pointer-events-none absolute left-2 top-1/2 size-3.5 -translate-y-1/2 text-muted-foreground" aria-hidden="true" /><input aria-label="Filter events" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Filter events" className="h-8 w-44 rounded-none border border-input bg-background pl-7 pr-2 text-xs outline-none focus:border-primary focus:ring-2 focus:ring-primary/20" /></div></div>}>
        {events.length === 0 ? <div className="py-8 text-center text-sm text-muted-foreground">No events match the current filter.</div> : <div className="space-y-4">{events.map((event, index) => <div key={event.id} className="flex gap-3"><div className="flex flex-col items-center"><span className={`mt-1.5 flex size-6 items-center justify-center border ${event.kind === "audit" ? "border-primary/30 bg-secondary text-primary" : "border-emerald-200 bg-emerald-50 text-emerald-800"}`}><span className="size-2 rounded-full bg-current" aria-hidden="true" /></span>{index < events.length - 1 ? <span className="mt-1 h-full w-px bg-border" /> : null}</div><div className="min-w-0 flex-1 border-b border-border pb-4 last:border-0"><div className="flex flex-wrap items-start justify-between gap-2"><div><div className="flex flex-wrap items-center gap-2"><p className="text-sm font-medium">{event.name}</p><StatusBadge label={event.kind} tone={event.kind === "audit" ? "info" : "healthy"} /><FailureBadge failureClass={event.failureClass} /></div><p className="mt-1 text-[11px] text-muted-foreground">{event.actor} · {event.resourceType}/{event.resourceId}</p></div><span className="drift-data text-[10px] text-muted-foreground">{event.occurredAt}</span></div><dl className="mt-3 grid gap-3 text-[11px] sm:grid-cols-3"><div><dt className="text-muted-foreground">Correlation</dt><dd className="drift-data mt-1">{event.correlationId}</dd></div><div><dt className="text-muted-foreground">Event ID</dt><dd className="drift-data mt-1">{event.id}</dd></div><div><dt className="text-muted-foreground">Payload</dt><dd className="mt-1">{event.payloadSummary}</dd></div></dl></div></div>)}</div>}
      </Panel>
      <div className="mt-6 grid gap-6 xl:grid-cols-2"><Panel title="Audit posture" description="Audit records are append-only evidence of actor and resource intent."><div className="space-y-3 text-xs leading-5 text-muted-foreground"><div className="flex gap-2"><ShieldCheck className="mt-0.5 size-4 shrink-0 text-primary" aria-hidden="true" />Actor type, actor ID, resource, correlation, and outcome labels remain visible.</div><div className="flex gap-2"><FileText className="mt-0.5 size-4 shrink-0 text-primary" aria-hidden="true" />Sensitive payloads are not reconstructed from the event list.</div></div></Panel><Panel title="Failure vocabulary" description="Failures are classified per target or event, not inferred from aggregate state."><div className="flex flex-wrap gap-2">{["device_offline", "policy_denied", "lease_conflict", "capability_mismatch", "indeterminate_completion"].map((failure) => <FailureBadge key={failure} failureClass={failure} />)}</div></Panel></div>
    </>
  )
}

function Summary({ icon: Icon, label, value, detail }: { icon: typeof Waypoints; label: string; value: string; detail: string }) {
  return <div className="border border-border bg-card p-4"><div className="flex items-center gap-2 text-primary"><Icon className="size-4" aria-hidden="true" /><span className="font-mono text-[10px] font-semibold uppercase tracking-[0.1em] text-muted-foreground">{label}</span></div><p className="drift-data mt-2 text-2xl font-semibold">{value}</p><p className="mt-1 text-[11px] text-muted-foreground">{detail}</p></div>
}

function isEventKind(value: string): value is EventKind | "all" {
  return value === "all" || value === "operational" || value === "audit"
}
