import { useMemo, useState } from "react"
import { Filter, Search } from "lucide-react"
import { ScrollArea } from "@/components/ui/scroll-area"
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from "@/components/ui/sheet"
import type { ControlPlaneSnapshot, EventKind, EventView } from "@/lib/domain/control-plane"
import { FailureBadge, MockNotice, PageIntro, StatusBadge } from "./shared"

export function EventsPage({ snapshot }: { snapshot: ControlPlaneSnapshot }) {
  const [kind, setKind] = useState<EventKind | "all">("all"); const [query, setQuery] = useState(""); const [selectedId, setSelectedId] = useState<string | null>(null)
  const events = useMemo(() => snapshot.events.filter((event) => (kind === "all" || event.kind === kind) && `${event.name} ${event.actor} ${event.resourceId} ${event.correlationId}`.toLowerCase().includes(query.toLowerCase())), [kind, query, snapshot.events])
  const selected = snapshot.events.find((event) => event.id === selectedId)
  return <><PageIntro eyebrow="OBSERVABILITY / EVENTS" title="Events and audit" description="A dense, searchable event ledger. Bounded metadata stays visible while raw payloads and sensitive evidence remain unavailable." actions={<StatusBadge label="Redacted view" tone="info" />} /><MockNotice>Payload bodies, screenshots, credentials, and protocol data are omitted. This is a mock-control-plane ledger only.</MockNotice>
    <div className="flex flex-wrap items-end gap-3 border-y border-border py-3" aria-label="Event filters"><label className="text-[10px] font-semibold uppercase tracking-[.08em] text-muted-foreground">Event type<select aria-label="Event type" value={kind} onChange={(event) => setKind(event.target.value as EventKind | "all")} className="mt-1 block h-8 rounded-none border border-input bg-background px-2 text-xs text-foreground"><option value="all">All events</option><option value="operational">Operational</option><option value="audit">Audit</option></select></label><label className="text-[10px] font-semibold uppercase tracking-[.08em] text-muted-foreground">Actor / device / correlation / time<div className="relative mt-1"><Search className="absolute left-2 top-2 size-3.5" aria-hidden="true" /><input aria-label="Search event ledger" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Filter ledger" className="h-8 rounded-none border border-input bg-background pl-7 pr-2 text-xs text-foreground" /></div></label><span className="ml-auto flex items-center gap-1 text-xs text-muted-foreground"><Filter className="size-3.5" aria-hidden="true" />{events.length} shown</span></div>
    <ScrollArea className="mt-4 h-[min(68vh,760px)] border border-border"><table className="w-full min-w-[940px] border-collapse text-left text-xs"><caption className="sr-only">Operational and audit event history</caption><thead className="sticky top-0 bg-background"><tr className="border-b border-border text-[10px] uppercase tracking-[.08em] text-muted-foreground"><th className="p-3">Time</th><th className="p-3">Event</th><th className="p-3">Type</th><th className="p-3">Actor</th><th className="p-3">Device / resource</th><th className="p-3">Correlation</th><th className="p-3">Severity</th></tr></thead><tbody>{events.map((event) => <EventRow key={event.id} event={event} onOpen={() => setSelectedId(event.id)} />)}</tbody></table>{events.length === 0 ? <div className="p-8 text-center text-sm text-muted-foreground">No events match these filters.</div> : null}</ScrollArea>
    <Sheet open={Boolean(selected)} onOpenChange={(open) => !open && setSelectedId(null)}><SheetContent className="w-full rounded-none sm:max-w-xl"><SheetHeader className="border-b border-border"><SheetTitle>{selected?.name ?? "Event detail"}</SheetTitle><SheetDescription>Sanitized, bounded event metadata.</SheetDescription></SheetHeader>{selected ? <dl className="grid gap-4 p-4 text-xs"><Detail label="Occurred" value={selected.occurredAt} /><Detail label="Actor" value={selected.actor} /><Detail label="Resource" value={`${selected.resourceType} / ${selected.resourceId}`} /><Detail label="Correlation ID" value={selected.correlationId} mono /><Detail label="Payload summary" value={selected.payloadSummary} /><div><dt className="text-muted-foreground">Failure classification</dt><dd className="mt-1"><FailureBadge failureClass={selected.failureClass} />{!selected.failureClass ? "None" : null}</dd></div></dl> : null}</SheetContent></Sheet>
  </> }
function EventRow({ event, onOpen }: { event: EventView; onOpen: () => void }) { return <tr className="border-b border-border/70 hover:bg-muted/50"><td className="p-3 text-muted-foreground">{event.occurredAt}</td><td className="p-3"><button onClick={onOpen} className="text-left font-medium underline-offset-2 hover:underline focus-visible:outline-2 focus-visible:outline-primary">{event.name}</button></td><td className="p-3"><StatusBadge label={event.kind} tone={event.kind === "audit" ? "info" : "healthy"} /></td><td className="p-3">{event.actor}</td><td className="p-3">{event.resourceType} · {event.resourceId}</td><td className="drift-data p-3 text-[10px]">{event.correlationId}</td><td className="p-3"><FailureBadge failureClass={event.failureClass} />{!event.failureClass ? <span className="text-muted-foreground">Normal</span> : null}</td></tr> }
function Detail({ label, value, mono = false }: { label: string; value: string; mono?: boolean }) { return <div><dt className="text-muted-foreground">{label}</dt><dd className={`mt-1 ${mono ? "drift-data text-[10px]" : ""}`}>{value}</dd></div> }
