import { useState, type FormEvent } from "react"
import { ArrowDownUp, History, MoveRight, Users } from "lucide-react"
import { Button } from "@/components/ui/button"
import type { ControlPlaneSnapshot, DispatchIntent } from "@/lib/domain/control-plane"
import { DeviceIdentity, FieldLabel, PageIntro, Panel, StatusBadge } from "./shared"
import { activeMemberships, textForDevice } from "./page-utils"

export function GroupsPage({ snapshot, dispatch }: { snapshot: ControlPlaneSnapshot; dispatch: DispatchIntent }) {
  const [deviceId, setDeviceId] = useState(snapshot.devices.find((device) => !snapshot.memberships.some((membership) => membership.deviceId === device.id && membership.state === "active"))?.id ?? snapshot.devices[0]?.id ?? "")
  const [groupId, setGroupId] = useState("ungrouped")
  const [position, setPosition] = useState("1")
  const [feedback, setFeedback] = useState("")
  const active = activeMemberships(snapshot.memberships)
  const ungrouped = snapshot.devices.filter((device) => !active.some((membership) => membership.deviceId === device.id))
  const selectedDevice = snapshot.devices.find((device) => device.id === deviceId)

  function moveDevice(event: FormEvent<HTMLFormElement>) {
    event.preventDefault()
    const mutation = dispatch({ type: "moveDeviceToGroup", deviceId, groupId, position: Math.max(1, Number(position) || 1) })
    setFeedback(mutation.message)
  }

  return (
    <>
      <PageIntro eyebrow="INVENTORY / GROUPS" title="Groups and membership" description="Review current placement, deterministic order, historical membership, and computed Ungrouped devices." actions={<StatusBadge label={`${snapshot.groups.length} active groups`} tone="info" />} />
      <div className="grid gap-6 xl:grid-cols-[minmax(0,1.35fr)_minmax(300px,0.65fr)]">
        <Panel title="Current placement" description="A device has at most one active membership. Ungrouped is computed, not persisted as a group.">
          <div className="grid gap-4 md:grid-cols-2">{snapshot.groups.map((group) => { const members = active.filter((membership) => membership.groupId === group.id).sort((left, right) => left.position - right.position); return <div key={group.id} className="border border-border p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-semibold">{group.name}</p><p className="drift-data mt-1 text-[10px] text-muted-foreground">{group.id} · row v{group.rowVersion}</p></div><StatusBadge label={group.state} tone={group.state === "active" ? "healthy" : "neutral"} /></div><ol className="mt-4 space-y-2" aria-label={`${group.name} member order`}>{members.length === 0 ? <li className="text-xs text-muted-foreground">No active members.</li> : members.map((membership) => { const member = snapshot.devices.find((device) => device.id === membership.deviceId); return <li key={membership.id} className="flex items-center gap-3 border-t border-border pt-2 text-xs"><span className="drift-data flex size-5 items-center justify-center border border-border text-[10px]">{membership.position}</span>{member ? <DeviceIdentity device={member} /> : <span className="text-muted-foreground">Unresolved device · {membership.deviceId}</span>}</li> })}</ol></div> })}<div className="border border-dashed border-primary/50 bg-secondary/40 p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-semibold">Ungrouped</p><p className="mt-1 text-[11px] text-muted-foreground">Computed from active memberships</p></div><Users className="size-4 text-primary" aria-hidden="true" /></div><ul className="mt-4 space-y-2">{ungrouped.length === 0 ? <li className="text-xs text-muted-foreground">All devices have an active group.</li> : ungrouped.map((device) => <li key={device.id} className="border-t border-border pt-2 text-xs"><DeviceIdentity device={device} /></li>)}</ul></div></div>
        </Panel>
        <Panel title="Move one device" description="Membership changes are one explicit typed intent with a target group and position.">
          <form className="space-y-4" onSubmit={moveDevice}><div><FieldLabel htmlFor="membership-device">Device</FieldLabel><select id="membership-device" value={deviceId} onChange={(event) => setDeviceId(event.target.value)} className="mt-1 h-9 w-full rounded-none border border-input bg-background px-2 text-sm outline-none focus:border-primary focus:ring-2 focus:ring-primary/20">{snapshot.devices.map((device) => <option key={device.id} value={device.id}>{device.displayName} · {device.stableIdentity}</option>)}</select></div><div><FieldLabel htmlFor="membership-group">Target group</FieldLabel><select id="membership-group" value={groupId} onChange={(event) => setGroupId(event.target.value)} className="mt-1 h-9 w-full rounded-none border border-input bg-background px-2 text-sm outline-none focus:border-primary focus:ring-2 focus:ring-primary/20"><option value="ungrouped">Computed Ungrouped</option>{snapshot.groups.filter((group) => group.state === "active").map((group) => <option key={group.id} value={group.id}>{group.name}</option>)}</select></div><div><FieldLabel htmlFor="membership-position">Position</FieldLabel><input id="membership-position" type="number" min="1" value={position} onChange={(event) => setPosition(event.target.value)} className="mt-1 h-9 w-full rounded-none border border-input bg-background px-2 font-mono text-sm outline-none focus:border-primary focus:ring-2 focus:ring-primary/20" /></div><div className="border border-border bg-muted/50 p-3 text-[11px] leading-5 text-muted-foreground"><ArrowDownUp className="mb-1 size-4 text-primary" aria-hidden="true" />{selectedDevice ? `${selectedDevice.displayName} will be ended from its current group before the new placement is appended.` : "Select a device."}</div><Button type="submit" className="w-full rounded-none" disabled={!deviceId}><MoveRight className="size-3.5" aria-hidden="true" />Move device</Button><p aria-live="polite" className="min-h-5 text-xs text-muted-foreground">{feedback}</p></form>
        </Panel>
      </div>
      <div className="mt-6"><Panel title="Membership history" description="Ended records explain prior placement without changing current group truth."><div className="overflow-x-auto"><table className="w-full min-w-[650px] border-collapse text-left text-xs"><caption className="sr-only">Device group membership history</caption><thead><tr className="border-b border-border text-[10px] uppercase tracking-[0.08em] text-muted-foreground"><th className="px-3 pb-3">Device</th><th className="px-3 pb-3">Group</th><th className="px-3 pb-3">Position</th><th className="px-3 pb-3">State</th><th className="px-3 pb-3">Started / ended</th></tr></thead><tbody>{snapshot.memberships.map((membership) => <tr key={membership.id} className="border-b border-border/70 last:border-0"><td className="px-3 py-3">{textForDevice(snapshot.devices, membership.deviceId)}</td><td className="px-3 py-3">{snapshot.groups.find((group) => group.id === membership.groupId)?.name ?? membership.groupId}</td><td className="drift-data px-3 py-3">{membership.position}</td><td className="px-3 py-3"><StatusBadge label={membership.state} tone={membership.state === "active" ? "healthy" : "neutral"} /></td><td className="drift-data px-3 py-3 text-[10px] text-muted-foreground">{membership.startedAt}{membership.endedAt ? ` → ${membership.endedAt}` : ""}</td></tr>)}</tbody></table></div></Panel></div>
      <div className="mt-6 flex items-start gap-2 border-t border-border pt-4 text-xs leading-5 text-muted-foreground"><History className="mt-0.5 size-4 text-primary" aria-hidden="true" />Group order is a current projection over append-only membership history. Bulk movement is intentionally not implied by this single-device action.</div>
    </>
  )
}
