import { useState, type FormEvent } from "react"
import { Check, Edit3, Globe2, Plus, Radar, Save, ShieldCheck, Trash2 } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from "@/components/ui/sheet"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import type { ControlPlaneSnapshot, DispatchIntent, NetworkProfileView, ScanCandidateView } from "@/lib/domain/control-plane"
import { EmptyState, FieldLabel, FailureBadge, MockNotice, PageIntro, Panel, StatusBadge } from "./shared"

export function NetworkProfilesPage({ snapshot, dispatch }: { snapshot: ControlPlaneSnapshot; dispatch: DispatchIntent }) {
  const [selectedProfileId, setSelectedProfileId] = useState(snapshot.networkProfiles[0]?.id ?? "new")
  const [name, setName] = useState(snapshot.networkProfiles[0]?.name ?? "")
  const [addressPolicy, setAddressPolicy] = useState(snapshot.networkProfiles[0]?.addressPolicy ?? "")
  const [ports, setPorts] = useState(snapshot.networkProfiles[0]?.ports.join(", ") ?? "5555")
  const [isDefault, setIsDefault] = useState(snapshot.networkProfiles[0]?.isDefault ?? false)
  const [candidateReason, setCandidateReason] = useState("")
  const [feedback, setFeedback] = useState("")
  const [profileDialogOpen, setProfileDialogOpen] = useState(false)
  const [scanDialogOpen, setScanDialogOpen] = useState(false)
  const [reviewCandidateId, setReviewCandidateId] = useState<string | null>(null)
  const selectedProfile = snapshot.networkProfiles.find((profile) => profile.id === selectedProfileId)
  const reviewCandidate = snapshot.scanCandidates.find((candidate) => candidate.id === reviewCandidateId)

  function selectProfile(profile: NetworkProfileView) { setSelectedProfileId(profile.id); setName(profile.name); setAddressPolicy(profile.addressPolicy); setPorts(profile.ports.join(", ")); setIsDefault(profile.isDefault); setFeedback("") }
  function beginNewProfile() { setSelectedProfileId("new"); setName(""); setAddressPolicy("192.0.2.0/24"); setPorts("5555"); setIsDefault(false); setFeedback(""); setProfileDialogOpen(true) }
  function parsedPorts() { return ports.split(",").map((value) => Number(value.trim())).filter((value) => Number.isInteger(value) && value > 0 && value <= 65535) }
  function saveProfile(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const parsed = parsedPorts(); if (!name.trim()) { setFeedback("Enter a profile name."); return }; if (!isDocumentationRange(addressPolicy)) { setFeedback("Use a CIDR within the documentation address ranges."); return }; if (parsed.length === 0) { setFeedback("Enter one or more ports from 1 through 65535."); return }; const mutation = selectedProfileId === "new" ? dispatch({ type: "createNetworkProfile", name, addressPolicy, ports: parsed, isDefault }) : dispatch({ type: "updateNetworkProfile", profileId: selectedProfileId, name, addressPolicy, ports: parsed, isDefault, rowVersion: selectedProfile?.rowVersion ?? 0 }); setFeedback(mutation.message); if (mutation.ok) setProfileDialogOpen(false) }
  function retireProfile() { if (selectedProfile) setFeedback(dispatch({ type: "retireNetworkProfile", profileId: selectedProfile.id, rowVersion: selectedProfile.rowVersion }).message) }
  function startScan() { setFeedback(dispatch({ type: "startScan", profileId: selectedProfileId }).message); setScanDialogOpen(false) }
  function decideCandidate(candidate: ScanCandidateView, approve: boolean) { setFeedback(dispatch({ type: "decideScanCandidate", candidateId: candidate.id, approve, reason: candidateReason }).message); setReviewCandidateId(null) }
  function registerCandidate(candidate: ScanCandidateView) { setFeedback(dispatch({ type: "registerScanCandidate", candidateId: candidate.id, displayName: `Mock ${candidate.host}` }).message); setReviewCandidateId(null) }

  return <>
    <PageIntro eyebrow="DISCOVERY / NETWORK PROFILES" title="Network Profiles" description="Define bounded, non-authoritative discovery policy separately from scan execution and candidate approval." actions={<div className="flex gap-2"><Button variant="outline" size="sm" onClick={beginNewProfile}><Plus className="size-3.5" aria-hidden="true" />New profile</Button><Button size="sm" onClick={() => setScanDialogOpen(true)} disabled={!selectedProfile || selectedProfile.state !== "active"}><Radar className="size-3.5" aria-hidden="true" />Configure scan</Button></div>} />
    <MockNotice>Address policies use documentation ranges and the transport is a deterministic mock. Saving or scanning opens no network socket and registers no real endpoint.</MockNotice>
    <Tabs defaultValue="profiles" className="mt-6"><TabsList className="h-auto flex-wrap rounded-none border border-border bg-background p-0" aria-label="Network profile views"><TabsTrigger value="profiles" className="rounded-none">Profiles</TabsTrigger><TabsTrigger value="scans" className="rounded-none">Discovery scans</TabsTrigger><TabsTrigger value="candidates" className="rounded-none">Pending candidates</TabsTrigger><TabsTrigger value="endpoints" className="rounded-none">Registered endpoints</TabsTrigger><TabsTrigger value="history" className="rounded-none">History</TabsTrigger></TabsList>
      <TabsContent value="profiles" className="mt-6"><Panel title="Profile catalog" description="Profile definitions constrain discovery; they do not establish an endpoint or approval."><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-xs"><caption className="sr-only">Network profile catalog</caption><thead><tr className="border-b border-border text-[10px] uppercase tracking-[0.08em] text-muted-foreground"><th className="pb-3">Name</th><th className="pb-3">Address policy</th><th className="pb-3">Ports</th><th className="pb-3">State</th><th className="pb-3">Default</th><th className="pb-3" /></tr></thead><tbody>{snapshot.networkProfiles.length === 0 ? <tr><td colSpan={6}><EmptyState label="No Network Profiles" detail="Create a bounded profile to continue." /></td></tr> : snapshot.networkProfiles.map((profile) => <tr key={profile.id} className="border-b border-border/70 last:border-0"><td className="py-3"><p className="font-medium">{profile.name}</p><p className="drift-data mt-1 text-[10px] text-muted-foreground">{profile.id} · row v{profile.rowVersion}</p></td><td className="py-3 font-mono text-[11px]">{profile.addressPolicy}</td><td className="py-3">{profile.ports.join(", ")}</td><td className="py-3"><StatusBadge label={profile.state} tone={profile.state === "active" ? "healthy" : profile.state === "retired" ? "neutral" : "attention"} /></td><td className="py-3">{profile.isDefault ? <Check className="size-4 text-primary" aria-label="Default profile" /> : "—"}</td><td className="py-3 text-right"><Button variant="outline" size="sm" onClick={() => { selectProfile(profile); setProfileDialogOpen(true) }}>Edit</Button></td></tr>)}</tbody></table></div></Panel></TabsContent>
      <TabsContent value="scans" className="mt-6"><Panel title="Discovery scans" description="A scan is an explicit mock intent against an active profile; it never approves candidates." action={<Button size="sm" onClick={() => setScanDialogOpen(true)} disabled={!selectedProfile || selectedProfile.state !== "active"}><Radar className="size-3.5" aria-hidden="true" />Configure scan</Button>}><ScanTable runs={snapshot.scanRuns} /></Panel></TabsContent>
      <TabsContent value="candidates" className="mt-6"><Panel title="Pending candidate review" description="Discovery, approval, and canonical registration remain independent transitions."><div className="mb-4 flex items-start gap-2 border border-border bg-muted/40 p-3 text-[11px] leading-5 text-muted-foreground"><ShieldCheck className="mt-0.5 size-4 shrink-0 text-primary" aria-hidden="true" />Candidate evidence is sanitized. Review opens a separate sheet before any mock decision is dispatched.</div><div className="space-y-2">{snapshot.scanCandidates.length === 0 ? <EmptyState label="No scan candidates" detail="Run a mock scan to populate the review queue." /> : snapshot.scanCandidates.map((candidate) => <button key={candidate.id} type="button" onClick={() => setReviewCandidateId(candidate.id)} className="flex w-full flex-wrap items-center justify-between gap-3 border border-border p-3 text-left transition-colors hover:bg-muted focus-visible:border-primary focus-visible:ring-3 focus-visible:ring-primary/30"><div><p className="text-sm font-medium">{candidate.host}:{candidate.port}</p><p className="drift-data mt-1 text-[10px] text-muted-foreground">{candidate.id} · {candidate.serial} · {candidate.fingerprint}</p><p className="mt-2 flex items-center gap-1.5 text-[11px] text-muted-foreground"><Globe2 className="size-3.5 text-primary" aria-hidden="true" />{candidate.evidenceSummary}</p></div><StatusBadge label={candidate.state.replaceAll("_", " ")} tone={candidate.state === "approved" || candidate.state === "registered" ? "healthy" : candidate.state === "rejected" || candidate.state === "expired" ? "danger" : "attention"} /></button>)}</div></Panel></TabsContent>
      <TabsContent value="endpoints" className="mt-6"><Panel title="Registered endpoints" description="Endpoint records are canonical identities distinct from unapproved scan candidates."><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-xs"><thead><tr className="border-b border-border text-[10px] uppercase tracking-[0.08em] text-muted-foreground"><th className="pb-3">Endpoint</th><th className="pb-3">Device</th><th className="pb-3">Address</th><th className="pb-3">Observed</th><th className="pb-3">State</th></tr></thead><tbody>{snapshot.endpoints.map((endpoint) => <tr key={endpoint.id} className="border-b border-border/70 last:border-0"><td className="py-3"><p className="font-medium">{endpoint.endpointType}</p><p className="drift-data mt-1 text-[10px] text-muted-foreground">{endpoint.id} · {endpoint.serial}</p></td><td className="drift-data py-3 text-[10px]">{endpoint.deviceId}</td><td className="py-3 font-mono text-[11px]">{endpoint.host}:{endpoint.port}</td><td className="py-3">{endpoint.observedAt}</td><td className="py-3"><StatusBadge label={endpoint.state} tone={endpoint.state === "current" ? "healthy" : endpoint.state === "retired" ? "neutral" : "attention"} /></td></tr>)}</tbody></table></div></Panel></TabsContent>
      <TabsContent value="history" className="mt-6"><Panel title="Scan history" description="Every attempted scan retains its profile reference and terminal outcome."><ScanTable runs={snapshot.scanRuns} /></Panel></TabsContent>
    </Tabs>
    <p aria-live="polite" className="mt-6 border-l-2 border-primary bg-secondary/60 p-3 text-xs text-muted-foreground">{feedback || "Discovery status feedback appears here. No external discovery is active."}</p>
    <Dialog open={profileDialogOpen} onOpenChange={setProfileDialogOpen}><DialogContent className="rounded-none sm:max-w-xl"><DialogHeader><DialogTitle>{selectedProfileId === "new" ? "Create Network Profile" : "Edit Network Profile"}</DialogTitle><DialogDescription>Profile definition is separate from scan execution and candidate approval.</DialogDescription></DialogHeader><form className="grid gap-4 sm:grid-cols-2" onSubmit={saveProfile}><div className="sm:col-span-2"><FieldLabel htmlFor="profile-name">Profile name</FieldLabel><input id="profile-name" value={name} onChange={(event) => setName(event.target.value)} className="mt-1 h-9 w-full rounded-none border border-input bg-background px-3 text-sm" required /></div><div><FieldLabel htmlFor="profile-address-policy">Address policy</FieldLabel><input id="profile-address-policy" value={addressPolicy} onChange={(event) => setAddressPolicy(event.target.value)} className="mt-1 h-9 w-full rounded-none border border-input bg-background px-3 font-mono text-xs" required /></div><div><FieldLabel htmlFor="profile-ports">Ports</FieldLabel><input id="profile-ports" value={ports} onChange={(event) => setPorts(event.target.value)} className="mt-1 h-9 w-full rounded-none border border-input bg-background px-3 font-mono text-xs" required /></div><label className="flex items-center gap-2 text-xs sm:col-span-2"><input type="checkbox" checked={isDefault} onChange={(event) => setIsDefault(event.target.checked)} className="size-4 accent-[var(--primary)]" />Use as default discovery policy</label><DialogFooter className="sm:col-span-2"><Button type="submit"><Save className="size-3.5" aria-hidden="true" />Save profile</Button>{selectedProfile ? <Button type="button" variant="destructive" onClick={retireProfile} disabled={selectedProfile.state === "retired"}><Trash2 className="size-3.5" aria-hidden="true" />Retire</Button> : null}</DialogFooter></form></DialogContent></Dialog>
    <Dialog open={scanDialogOpen} onOpenChange={setScanDialogOpen}><DialogContent className="rounded-none"><DialogHeader><DialogTitle>Configure mock discovery scan</DialogTitle><DialogDescription>Runs only against the selected bounded profile. No external discovery or endpoint registration occurs.</DialogDescription></DialogHeader><dl className="border-y border-border py-3 text-xs"><div className="flex justify-between gap-4"><dt className="text-muted-foreground">Profile</dt><dd>{selectedProfile?.name ?? "None selected"}</dd></div><div className="mt-2 flex justify-between gap-4"><dt className="text-muted-foreground">Address policy</dt><dd className="font-mono">{selectedProfile?.addressPolicy ?? "—"}</dd></div></dl><DialogFooter><Button onClick={startScan} disabled={!selectedProfile || selectedProfile.state !== "active"}><Radar className="size-3.5" aria-hidden="true" />Start mock scan</Button></DialogFooter></DialogContent></Dialog>
    <Sheet open={reviewCandidateId !== null} onOpenChange={(open) => { if (!open) setReviewCandidateId(null) }}><SheetContent className="w-full rounded-none sm:max-w-md"><SheetHeader><SheetTitle>Candidate review</SheetTitle><SheetDescription>Approval is required before the separate mock registration action is offered.</SheetDescription></SheetHeader>{reviewCandidate ? <div className="space-y-5 px-4 pb-4"><div className="border-y border-border py-4"><p className="font-medium">{reviewCandidate.host}:{reviewCandidate.port}</p><p className="drift-data mt-1 text-[10px] text-muted-foreground">{reviewCandidate.id} · {reviewCandidate.serial}</p><p className="mt-3 text-xs text-muted-foreground">{reviewCandidate.evidenceSummary}</p></div><div><FieldLabel htmlFor="candidate-reason">Decision rationale</FieldLabel><textarea id="candidate-reason" value={candidateReason} onChange={(event) => setCandidateReason(event.target.value)} rows={4} className="mt-1 w-full rounded-none border border-input bg-background p-2 text-xs" placeholder="Bounded operator rationale" /></div><div className="flex flex-wrap gap-2">{reviewCandidate.state === "pending_approval" ? <><Button onClick={() => decideCandidate(reviewCandidate, true)}><Check className="size-3.5" aria-hidden="true" />Approve</Button><Button variant="outline" onClick={() => decideCandidate(reviewCandidate, false)}><Edit3 className="size-3.5" aria-hidden="true" />Reject</Button></> : null}{reviewCandidate.state === "approved" ? <Button variant="secondary" onClick={() => registerCandidate(reviewCandidate)}><ShieldCheck className="size-3.5" aria-hidden="true" />Register mock candidate</Button> : null}</div></div> : null}</SheetContent></Sheet>
  </>
}

function ScanTable({ runs }: { runs: ControlPlaneSnapshot["scanRuns"] }) { return <div className="overflow-x-auto"><table className="w-full min-w-[650px] text-left text-xs"><thead><tr className="border-b border-border text-[10px] uppercase tracking-[0.08em] text-muted-foreground"><th className="pb-3">Run</th><th className="pb-3">Profile</th><th className="pb-3">Requested</th><th className="pb-3">Completed</th><th className="pb-3">State</th></tr></thead><tbody>{runs.map((run) => <tr key={run.id} className="border-b border-border/70 last:border-0"><td className="drift-data py-3 text-[10px]">{run.id}</td><td className="drift-data py-3 text-[10px]">{run.networkProfileId}</td><td className="py-3">{run.requestedAt}</td><td className="py-3"><span>{run.finishedAt ?? "—"}</span>{run.failureClass ? <FailureBadge failureClass={run.failureClass} /> : null}</td><td className="py-3"><StatusBadge label={run.state} tone={run.state === "completed" ? "healthy" : run.state === "failed" ? "danger" : "info"} /></td></tr>)}</tbody></table></div> }
function isDocumentationRange(value: string) { return /^(192\.0\.2|198\.51\.100|203\.0\.113)\.\d{1,3}\/([0-2]?\d|3[0-2])$/.test(value.trim()) }
