import { useMemo, useState, type FormEvent } from "react"
import { Save } from "lucide-react"
import { Button } from "@/components/ui/button"
import { ScrollArea } from "@/components/ui/scroll-area"
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from "@/components/ui/sheet"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import type { ControlPlaneSnapshot, DispatchIntent, SettingScope } from "@/lib/domain/control-plane"
import { FieldLabel, MockNotice, PageIntro, StatusBadge } from "./shared"

const scopes: { value: SettingScope; label: string }[] = [{ value: "workspace", label: "Workspace" }, { value: "control_plane", label: "Control plane" }, { value: "edge_host", label: "Edge host" }, { value: "device", label: "Device" }, { value: "automation_agent", label: "Automation agent" }, { value: "operator_preference", label: "Operator preference" }]
export function SettingsPage({ snapshot, dispatch }: { snapshot: ControlPlaneSnapshot; dispatch: DispatchIntent }) {
  const [scope, setScope] = useState<SettingScope>("workspace"); const [selectedId, setSelectedId] = useState<string | null>(null); const selected = snapshot.settings.find((setting) => setting.id === selectedId); const [valueJson, setValueJson] = useState(""); const [feedback, setFeedback] = useState("")
  const settings = useMemo(() => snapshot.settings.filter((setting) => setting.scope === scope), [scope, snapshot.settings])
  function open(id: string) { const setting = snapshot.settings.find((candidate) => candidate.id === id); setSelectedId(id); setValueJson(setting?.valueJson ?? ""); setFeedback("") }
  function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!selected) return; setFeedback(dispatch({ type: "updateSetting", settingId: selected.id, valueJson, rowVersion: selected.rowVersion }).message) }
  return <><PageIntro eyebrow="CONFIGURATION / SCOPED SETTINGS" title="Settings" description="Settings are separated by authority scope. Workspace display preferences are never conflated with safety-critical policy." actions={<StatusBadge label={`${snapshot.settings.length} settings`} tone="info" />} /><MockNotice>All settings are mock projections. Browser display preferences cannot authorize device control.</MockNotice>
    <Tabs defaultValue="settings" className="mt-6"><TabsList className="rounded-none border border-border bg-background p-0" aria-label="Settings views"><TabsTrigger value="settings" className="rounded-none">Settings</TabsTrigger><TabsTrigger value="history" className="rounded-none">History</TabsTrigger></TabsList><TabsContent value="settings" className="mt-4"><Tabs value={scope} onValueChange={(value) => setScope(value as SettingScope)}><TabsList className="h-auto max-w-full flex-wrap justify-start rounded-none border border-border bg-background p-0" aria-label="Setting scopes">{scopes.map((item) => <TabsTrigger key={item.value} value={item.value} className="rounded-none text-xs">{item.label}</TabsTrigger>)}</TabsList><TabsContent value={scope}><ScrollArea className="mt-4 h-[min(65vh,720px)] border border-border"><table className="w-full min-w-[760px] text-left text-xs"><thead className="sticky top-0 bg-background"><tr className="border-b border-border text-[10px] uppercase tracking-[.08em] text-muted-foreground"><th className="p-3">Setting</th><th className="p-3">State</th><th className="p-3">Risk</th><th className="p-3">Value</th><th className="p-3">Version</th></tr></thead><tbody>{settings.map((setting) => <tr key={setting.id} className="border-b border-border/70 hover:bg-muted/50"><td className="p-3"><button onClick={() => open(setting.id)} className="font-medium hover:underline">{setting.key}</button></td><td className="p-3"><StatusBadge label={setting.state} tone={setting.state === "active" ? "healthy" : "neutral"} /></td><td className="p-3"><StatusBadge label={setting.risk === "safety_critical" ? "Safety critical" : "Preference"} tone={setting.risk === "safety_critical" ? "attention" : "neutral"} /></td><td className="p-3 text-muted-foreground">{setting.valueSummary}</td><td className="drift-data p-3 text-[10px]">v{setting.rowVersion}</td></tr>)}</tbody></table></ScrollArea></TabsContent></Tabs></TabsContent><TabsContent value="history" className="mt-4"><section className="border border-border"><h2 className="border-b border-border p-3 text-xs font-semibold uppercase tracking-[.08em]">Setting history</h2><div className="divide-y divide-border">{snapshot.settingHistory.map((entry) => <div key={entry.id} className="flex flex-wrap justify-between gap-2 p-3 text-[11px]"><span>{entry.key} · {entry.valueJson}</span><span className="drift-data text-[10px] text-muted-foreground">{entry.scope} · {entry.actorType} · {entry.changedAt}</span></div>)}</div></section></TabsContent></Tabs>
    <Sheet open={Boolean(selected)} onOpenChange={(openState) => !openState && setSelectedId(null)}><SheetContent className="w-full rounded-none sm:max-w-xl"><SheetHeader className="border-b border-border"><SheetTitle>{selected?.key ?? "Setting"}</SheetTitle><SheetDescription>Scope: {selected?.scope ?? "—"}. Updates retain typed validation and optimistic row versioning.</SheetDescription></SheetHeader>{selected ? <form onSubmit={save} className="space-y-4 p-4"><div className="flex gap-2"><StatusBadge label={selected.risk === "safety_critical" ? "Safety critical" : "Low-risk preference"} tone={selected.risk === "safety_critical" ? "attention" : "neutral"} /><StatusBadge label={selected.valueKind} tone="info" /></div><div><FieldLabel htmlFor="setting-value">Value JSON</FieldLabel><textarea id="setting-value" value={valueJson} onChange={(event) => setValueJson(event.target.value)} rows={6} className="mt-1 w-full rounded-none border border-input bg-background p-3 font-mono text-xs" /></div><p className="text-[11px] text-muted-foreground">Allowed values: {selected.allowedValues?.join(", ") ?? (selected.minValue !== undefined ? `${selected.minValue}–${selected.maxValue}` : "service constrained")}</p><Button type="submit" disabled={selected.state === "retired"}><Save className="size-3.5" aria-hidden="true" />Save setting</Button><p aria-live="polite" className="text-xs text-muted-foreground">{feedback}</p></form> : null}</SheetContent></Sheet>
  </> }
