import { ScrollArea } from "@/components/ui/scroll-area"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import type { ControlPlaneSnapshot, DispatchIntent } from "@/lib/domain/control-plane"
import { MockNotice, PageIntro, StatusBadge } from "./shared"

export function WorkflowsPage({ snapshot }: { snapshot: ControlPlaneSnapshot; dispatch: DispatchIntent }) {
  return <><PageIntro eyebrow="EXECUTION / WORKFLOWS" title="Workflows" description="Definitions, immutable version facts, and promoted skills are separate from run admission and target execution." actions={<StatusBadge label="Browser-only" tone="info" />} /><MockNotice>Definitions are typed mock projections. No workflow worker, package runtime, shell, or device adapter is available from this console.</MockNotice>
    <Tabs defaultValue="definitions"><TabsList className="rounded-none border border-border bg-background p-0" aria-label="Workflow views"><TabsTrigger value="definitions" className="rounded-none">Definitions</TabsTrigger><TabsTrigger value="versions" className="rounded-none">Versions</TabsTrigger><TabsTrigger value="skills" className="rounded-none">Skills</TabsTrigger></TabsList>
      <TabsContent value="definitions"><ScrollArea className="mt-4 h-[min(65vh,700px)] border border-border"><table className="w-full min-w-[760px] text-left text-xs"><thead className="sticky top-0 bg-background"><tr className="border-b border-border text-[10px] uppercase tracking-[.08em] text-muted-foreground"><th className="p-3">Workflow</th><th className="p-3">State</th><th className="p-3">Targets</th><th className="p-3">Safety</th><th className="p-3">Steps</th></tr></thead><tbody>{snapshot.workflows.map((workflow) => <tr key={workflow.id} className="border-b border-border/70"><td className="p-3"><p className="font-medium">{workflow.name}</p><p className="drift-data mt-1 text-[10px] text-muted-foreground">{workflow.id}</p></td><td className="p-3"><StatusBadge label={workflow.state} tone={workflow.state === "published" ? "healthy" : "attention"} /></td><td className="p-3">{workflow.targetSelector}</td><td className="p-3 text-muted-foreground">{workflow.safetySummary}</td><td className="p-3">{workflow.stepCount}</td></tr>)}</tbody></table></ScrollArea></TabsContent>
      <TabsContent value="versions"><div className="mt-4 space-y-2">{snapshot.workflows.map((workflow) => <div key={workflow.id} className="flex justify-between border border-border p-3 text-xs"><span>{workflow.name}</span><span className="drift-data">version {workflow.version}</span></div>)}</div></TabsContent>
      <TabsContent value="skills"><div className="mt-4 grid gap-3 md:grid-cols-2">{snapshot.skills.map((skill) => <article key={skill.id} className="border border-border p-4"><div className="flex justify-between gap-2"><p className="text-sm font-semibold">{skill.name}</p><StatusBadge label={skill.trust} tone={skill.trust === "approved" ? "healthy" : "attention"} /></div><p className="drift-data mt-2 text-[10px] text-muted-foreground">{skill.id} · v{skill.version}</p><p className="mt-3 text-xs text-muted-foreground">{skill.capabilities.join(", ")}</p></article>)}</div></TabsContent>
    </Tabs>
  </> }
